version: "3.9"

services:

  appfrontend:
    container_name: appfrontend
    build:
      context: .
    #restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
